name: Upload files to an archive.org item
author: Ben Welsh
description: Automatically save files with the Internet Archive

branding:
  icon: upload-cloud
  color: white

inputs:
  access-key:
    description: Your archive.org access key.
    required: true
  secret-key:
    description: Your archive.org secret key
    required: true
  identifier:
    description: The unique identifier of the archive.org item where the file will be stored
    required: true
  files:
    description: The file or folder path inside the action's filesystem to upload
    required: true

runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version:  3.9
        cache: 'pip'

    - id: install-deps
      name: Install Python dependencies
      run: pip install -r requirements.txt
      shell: bash

    - id: upload-files
      name: Upload files
      run: python ${{ github.action_path }}/upload.py
      shell: bash
      env:
          access-key: ${{ inputs.access-key }}
          secret-key: ${{ inputs.secret-key }}
          identifier: ${{ inputs.identifier }}
          files: ${{ inputs.files }}
